language: csharp
os: linux
dotnet: 3.1.300
mono: none
sudo: false # use the new container-based Travis infrastructure
script:
 - dotnet restore 
 - dotnet tool restore
 - dotnet paket install
 - dotnet build
 - dotnet test
 - ./check-data.sh
